language: python

python:
  - "2.7"
  - "3.6"
  
install:
  - sudo apt-get update
  - pip install -U pip
  - python setup.py install # install your package
  - pip install coveralls
  
  # also install requirements .txt
  - pip install -r requirements.txt
  
script:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      py.test;
    else
      pytest;
    fi
  - coverage run --source=yamlsettings -m pytest

after_success:
  - coveralls
